name: "Deploy Application to Raspberry Pi"

on:
  push:
    branches:
      - master

jobs:
  deploy-to-pi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            # Alten Container stoppen und l√∂schen
            docker stop movie-app || true
            docker rm movie-app || true

            # Neueste Version vom Docker Hub ziehen
            docker pull ${{ secrets.DOCKERHUB_TAG }}

            # Container starten mit MongoDB ENV
            docker run -d \
              --name movie-app \
              -p 80:8080 \
              -e MONGODB_URI="${{ secrets.MONGODB_URI }}" \
              ${{ secrets.DOCKERHUB_TAG }}
